feat: custom context
pavlovcik/ubiquibot pull request #29
Opened 2023-10-23 09:09 UTC by whilefoo

2023-10-23 11:57 UTC, pavlovcik commented on src/bindings/event.ts
> +import { Context as ProbotContext } from "probot";
You sure about the typecasting here? Seems like you're killing the point of the typing?

2023-10-23 12:00 UTC, pavlovcik commented on src/types/context.ts
Are you sure this is sufficient to solve the business problem? It doesn't look like it.

2023-10-23 12:01 UTC, pavlovcik requested changes
There's some build errors and questions.

2023-10-23 14:10 UTC, whilefoo commented on src/types/context.ts
Why not?

2023-10-23 17:25 UTC, whilefoo commented on src/types/context.ts
I can change it a class with helper functions like getOctokit, getPayload, getEvent, getConfig but other than that I don't see what else could be added

2023-10-23 21:54 UTC, pavlovcik commented on src/types/context.ts
Its fine. Can you fix the build errors

2023-10-24 07:33 UTC, whilefoo commented on src/types/context.ts
two build errors in `processors.ts` are from your code so I'm not sure why it's not working and one error is from `wallet.test.ts` because now it needs a mocked context but I don't think that test is even needed, should I just remove it?

2023-10-24 12:47 UTC, pavlovcik commented on src/types/context.ts
I think we should keep all the tests. It seems like a waste to write tests and then delete instead of fixing them when new code is introduced. Please address those and I'll merge it in.

2023-10-25 10:13 UTC, whilefoo commented on src/types/context.ts
I just realized that adapters will have to be moved into context aswell, because some tables like logs and wallet use the context, and having adapters in runtime will mean they will override on each request. 

There are two choices:
1. change adapters' functions to accept additional parameter `context` so they can stay as global runtime 
2. move adapters to context

2023-10-26 15:11 UTC, whilefoo commented on src/types/context.ts
@pavlovcik what do you think?

2023-10-26 16:19 UTC, pavlovcik commented on src/types/context.ts
Hard to say cause I dont think I understand the tradeoff well enough.

2023-10-30 10:22 UTC, pavlovcik approved these changes

2023-10-30 10:22 UTC, merged