feat: remove context from adapters and pass it by parameter
pavlovcik/ubiquibot pull request #51
Opened 2023-11-19 22:50 UTC by whilefoo

Before adapters were initialized by passing probot's context to the constructor but this a problem when multiple events are received simultaneously...the latest event overwrote the previous adapters so if any previous events were still processing and using logger it would post under wrong repository/issue

2023-11-19 22:51 UTC, whilefoo commented
@pavlovcik

2023-11-19 22:53 UTC, pavlovcik commented on src/adapters/supabase/helpers/tables/access.ts
> +      this.runtime.logger.error(null, error.message, error);
Don't think you're using this correctly.

2023-11-19 22:54 UTC, pavlovcik commented on src/adapters/supabase/helpers/tables/logs.ts
> +
Logging works fine why did you change this

2023-11-19 22:56 UTC, pavlovcik commented
> Before adapters were initialized by passing probot's context to the constructor but this a problem when multiple events are received simultaneously...the latest event overwrote the previous adapters so if any previous events were still processing and using logger it would post under wrong repository/issue

I don't understand how this is possible, because I thought you fixed this with your other pull request by passing in the context all the way from the program entry to the deepest nested functions.

2023-11-19 23:43 UTC, pavlovcik commented on src/adapters/supabase/helpers/tables/logs.ts
> +
It looks like you're removing logic around the comment getting colorized?

2023-11-19 23:53 UTC, pavlovcik requested changes
Change the function signature to be more developer experience friendly. More notes above.

2023-11-20 10:27 UTC, whilefoo commented
> So it sounds like it is logger specific

it also affects other tables that use the probot context.

> It is a logger function so intuitively the log string should definitely be the first parameter. In addition, I see that you have instances where you are passing `null` as the `Context` object which means that it should be the later (and apparently optional) parameters.

I also wanted to put it as last optional parameter but the reason I put it as the first parameter is that you can't forget about it. If we put it as last optional parameter I think it will be often forgotten.

Another option is to have a logger inside the Context so you don't need to pass context and have Runtime as global logger where context is not available.

2023-11-20 11:50 UTC, whilefoo commented on src/adapters/supabase/helpers/tables/logs.ts
> +
I just simplified it

2023-11-20 12:13 UTC, pavlovcik commented
> Another option is to have a logger inside the Context

We can override the built in one for probot possibly. I vaguely recall they have a deprecated logger property on the probot context object. 

I think that approach might be the cleanest.

2023-11-21 01:47 UTC, pavlovcik commented on src/adapters/index.ts
> +      logs: new Logs(supabaseClient, null, env.LOG_ENVIRONMENT, env.LOG_RETRY_LIMIT, env.LOG_LEVEL),
I feel like params that are expected to be `null` should be last.

2023-11-21 01:47 UTC, pavlovcik commented on src/adapters/index.ts
> +      logs: new Logs(supabaseClient, null, env.LOG_ENVIRONMENT, env.LOG_RETRY_LIMIT, env.LOG_LEVEL),
I feel like params that are expected to be `null` should be last.

2023-11-21 01:53 UTC, pavlovcik commented on src/handlers/comment/handlers/issue/relevance-scoring.ts
> +      context.logger.error("Correct length is not defined", {
I might need to `throw` this error

2023-11-21 01:56 UTC, pavlovcik approved these changes
I trust that the code is stable so I'm merging it.

2023-11-21 01:56 UTC, merged

2023-11-21 01:59 UTC, pavlovcik commented on src/adapters/index.ts
> +      logs: new Logs(supabaseClient, null, env.LOG_ENVIRONMENT, env.LOG_RETRY_LIMIT, env.LOG_LEVEL),
0724395cfeb6ba4bce624bf41d99ff3d0f72ea00