feat: integrate infrastructure
pavlovcik/ubiquibot pull request #52
Opened 2023-11-22 10:26 UTC by wannacfuture

Resolves #

Quality Assurance:

2023-11-22 10:33 UTC, wannacfuture commented on src/handlers/comment/handlers/issue/issue-closed.ts
> +  await dispatchWorkflow("wannacfuture", "UbiquitBot-Bridge", "bridge.yml", {
The only thing we need to consider is this line.

Should we set the path as the same organization, and `ubiquibot-config` repo?

And the user can set the config repo as my bridge repo.
@pavlovcik

2023-11-22 10:34 UTC, wannacfuture reviewed
@pavlovcik

2023-11-22 13:20 UTC, wannacfuture commented on src/handlers/comment/handlers/issue/issue-closed.ts
> +  await dispatchWorkflow("wannacfuture", "UbiquitBot-Bridge", "bridge.yml", {
Fixed.

2023-11-23 04:31 UTC, pavlovcik requested changes
Do me a favor. There's several `any` type casts. I would appreciate if you spend another hour or so setting specific types for type safety wherever you can find, especially in the new code you introduced. Good work on the pull request!

2023-11-23 04:35 UTC, pavlovcik commented
This is an interesting approach. For some reason I figured that the `secretToken` would be set in the `ubiquibot-config` repo secrets instead. Is transmitting it from the other repo the superior choice? If so, why?

https://github.com/wannacfuture/ubiquibot-config/blob/d3e49c8f44183a033459cb1257695df4018c95a5/.github/workflows/bridge.yml#L21-L23

2023-11-23 10:44 UTC, wannacfuture commented
> This is an interesting approach. For some reason I figured that the `secretToken` would be set in the `ubiquibot-config` repo secrets instead. Is transmitting it from the other repo the superior choice? If so, why?
> 
> https://github.com/wannacfuture/ubiquibot-config/blob/d3e49c8f44183a033459cb1257695df4018c95a5/.github/workflows/bridge.yml#L21-L23

We need to return the response to the original repo.
And for that, we need to put secret token as the payload for the request.
https://github.com/wannacfuture/ubiquibot-config/blob/d3e49c8f44183a033459cb1257695df4018c95a5/.github/workflows/bridge.yml#L42C1-L48C172

2023-11-24 01:25 UTC, pavlovcik commented
I think it makes sense to rename `bridge.yml` to `compute.yml` or something of the like, because I don't want it to be confused with bridges as we see in DeFi.

2023-11-24 02:00 UTC, pavlovcik commented
Is there any extra setup required other than pushing `bridge.yml` to `@pavlovcik/ubiquibot-config`? I'm leaning towards merging this so I can continue working.

2023-11-26 01:45 UTC, merged